# Generated by Django 3.2 on 2022-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
